[versions]
agp = "8.7.0"
firebaseBom = "33.6.0"
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.6"
activityCompose = "1.9.2"
composeBom = "2024.04.01"
navigationCompose = "2.8.2"
navigation = "2.8.2"
material-icons = "1.1.0"
roomKtx = "2.7.0-rc03"
material3Version = "1.3.1"
foundationDesktop = "1.7.0"
appcompat = "1.7.0"
activity = "1.7.2"
lifecycle = "2.6.2"
room = "2.7.0-rc03"
gson = "2.10"
adapters = "3.2.0-alpha11"
uiDesktop = "1.4.3"
runtimeLivedata = "1.7.5"
googleGmsGoogleServices = "4.4.2"
firebaseAuth = "23.2.0"
osmdroid = "6.1.16"
osmbonuspack = "6.9.0"
vico = "1.13.1"
mail = "1.6.7"
apache-poi = "5.2.3"
apache-poi-ooxml-lite = "5.2.3"
runtimeAndroid = "1.7.8"
coroutines = "1.6.1"
roomExternalAntlr = "2.7.0-rc03"
kotlinx-metadata-jvm = "0.6.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
google-firebase-auth = { module = "com.google.firebase:firebase-auth" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
material-icons = { module = "androidx.compose.material:material-icons-extended", version = "1.7.3" }
compose = "androidx.compose.material:material:<version>"
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
androidx-adapters = { group = "androidx.databinding", name = "adapters", version.ref = "adapters" }
androidx-ui-desktop = { group = "androidx.compose.ui", name = "ui-desktop", version.ref = "uiDesktop" }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
osmdroid-android = { group = "org.osmdroid", name = "osmdroid-android", version.ref = "osmdroid" }
osmdroid-routing = { group = "com.github.MKergall", name = "osmbonuspack", version = "6.9.0" }
osmdroid-wms = { group = "org.osmdroid", name = "osmdroid-wms", version.ref = "osmdroid" }
osmdroid-mapsforge = { group = "org.osmdroid", name = "osmdroid-mapsforge", version.ref = "osmdroid" }
osmdroid-third-party = { group = "org.osmdroid", name = "osmdroid-third-party", version.ref = "osmdroid" }
osmdroid-bonuspack = { group = "com.github.MKergall", name = "osmbonuspack", version.ref = "osmbonuspack" }
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }
android-mail = { group = "com.sun.mail", name = "android-mail", version.ref = "mail" }
android-activation = { group = "com.sun.mail", name = "android-activation", version.ref = "mail" }
apache-poi = { group = "org.apache.poi", name = "poi", version.ref = "apache-poi" }
apache-poi-ooxml = { group = "org.apache.poi", name = "poi-ooxml", version.ref = "apache-poi" }
apache-poi-ooxml-lite = { group = "org.apache.poi", name = "poi-ooxml-lite", version.ref = "apache-poi-ooxml-lite" }
androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
androidx-room-external-antlr = { group = "androidx.room", name = "room-external-antlr", version.ref = "roomExternalAntlr" }
kotlinx-metadata-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-metadata-jvm", version.ref = "kotlinx-metadata-jvm" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }


